name: Lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install clang-tidy
      run: sudo apt-get install clang-tidy
    - name: clang-tidy
      run: find . -path "*/src/*.c" \
        -or -path "*/include/*.h" \
        | xargs -i clang-tidy \
        -checks=llvm-header-guard,* \
        -warnings-as-errors=* \
        {} \
        -- -Iinclude
