name: Style
on: push

jobs:
  style-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install clang-10
      run: |
        wget -O clang.tar.gz --progress=dot https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
        tar -xvf clang.tar.gz
        mv "clang+llvm-10*" "clang"
    - name: fmt help
      run: clang/bin/clang-format --version && clang/bin/clang-format --help 
    - name: clang-format
      run: find . -path "*/src/*.c" -or -path "*/include/*.h" | xargs clang/bin/clang-format -style=file -dry-run -Werror
