name: Style
on: push

jobs:
  style-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install clang-10
      run: |
        wget -O clang.tar.gz --progress=dot https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz
        tar -xf clang.tar.gz
        rm clang.tar.gz
        mv clang* clang-10
    - name: clang-format
      run: find libprim prim_app -name *.c -or -name *h | xargs clang-10/bin/clang-format -style=file -dry-run -Werror
