name: Style
on: push

jobs:
  style-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install clang-format-8
      run: sudo apt-get install clang-format
    - name: fmt help
      run: clang-format --version && clang-format --help 
    - name: clang-format
      run: find . -path "*/src/*.c" -or -path "*/include/*.h" | xargs clang-format -style=file -dry-run -Werror
